import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api, RouterOutputs } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex flex-col w-full">
      <div className=""><SignOutButton /></div>
      <div className='flex gap-3 w-full'>
        <Image 
          className="h-14 w-14 rounded-full"
          src={user.profileImageUrl}
          alt="Profile image"
          width={56}
          height={56}
        />
        <input
          className="bg-transparent outline outline-1 outline-slate-400 grow px-2 rounded"
          placeholder="Say something..."
        />
      </div>
    </div>
  )
}

type PostWithUser = RouterOutputs["post"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="px-2 py-8 border-b border-slate-400 flex gap-2 items-center mx-6">
      <Image
        className="h-12 w-12 rounded-full"
        src={author.profileImageUrl}
        alt="Author Image"
        width="56"
        height="56"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-500">
          <span className="font-semibold">{`@${author.id}`}</span>
          <span className="px-2">·</span>
          <span className="font-light">{`${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {

  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();

  console.log(data)
  
  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl h-full border-x border-slate-400">
          <div className='border-b border-slate-400 p-4 flex'>
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {!!user.isSignedIn && CreatePostWizard()}
          </div>
          <div className='flex flex-col'>
            {data?.map((post) => <PostView {...post} key={post.post.id}/>
             )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
